### ISSUE TITLE
Strange behavior with Badges and themelib

### ISSUE THREAD

**Issue by spacecowboy2015** [coolstar/themelib#1]
Dear coolstar, thank you for the very cool tweak themelib. With themelib I have the good old badges back. But I have an issue since 8.1.2 on my 6+ until 8.3. As you can see in my screenshot: the badges on phone and facetime have strange circles in it, and they change the colours: sometimes they are green, red, brown or yellow. I tried to solve the issue by deinstalling winterboard, SBHTML, GroovyLock but the only chance to "solve" the problem is to uninstall themelib. But I love the classic badges. Do you have any idea?

Best regards Michael

![img_0030](https://cloud.githubusercontent.com/assets/13098577/8403767/bcebb136-1e47-11e5-8c9a-babfd99c5721.PNG)

**Comment by coolstar** [comment]
Hi, ThemeLib is no longer maintained as a separate tweak. We are now part of Anemone. Are you getting the same issue on the latest Anemone nightly?

Nightly builds are in this repo: https://anemonetheming.com/nightly/

**Comment by spacecowboy2015** [comment]
Hi, thank you. That solved my problem :-) But I need Winterbord too, is this right? Or do I have to uninstall Winterboard and iconomatic?

Best regards
Michael

Absender: coolstar notifications@github.com
Antworten: coolstar/themelib reply@reply.github.com>
Datum: 29. Juni 2015 at 10:21:34
Empfänger: coolstar/themelib themelib@noreply.github.com>
CC: spacecowboy2015 m@betterdays.de>
Betreff:  Re: [themelib] Strange behavior with Badges and themelib (#1)  

Hi, ThemeLib is no longer maintained as a separate tweak. We are now part of Anemone. Are you getting the same issue on the latest Anemone nightly?

Nightly builds are in this repo: https://anemonetheming.com/nightly/
